questions =  [
    {"id": 0, "question": "Capitalism is the best economic system ever created", "effects": {"right": 1}},
    {"id": 1, "question": "Most social programs should be abolished in favor of private charity", "effects": {"right": 1}},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth", "effects": {"right": 1}},
    {"id": 3, "question": "Ideally, only property owners should be allowed to vote", "effects": {"right": 1}},
    {"id": 4, "question": "Free market is better at allocating resources than central planning", "effects": {"right": 1}},
    {"id": 5, "question": "Communism has failed every time it was tried", "effects": {"right": 1}},
    {"id": 6, "question": "The West is wealthy because of hard work and innovation rather than colonialism and exploitation", "effects": {"right": 1}},
    {"id": 7, "question": "Labor unions usually do more harm than good", "effects": {"right": 1}},
    {"id": 8, "question": "Real Communism has been tried and it was glorious", "effects": {"right": -1}},
    {"id": 9, "question": "The means of production should be owned collectively by the workers", "effects": {"right": -1}},
    {"id": 10, "question": "Landlords are parasites who contribute nothing to society and should be eliminated", "effects": {"right": -1}},
    {"id": 11, "question": "All land should be owned by the people's government as opposed to private property owners", "effects": {"right": -1}},
    {"id": 12, "question": "Key industries should be nationalized", "effects": {"right": -1}},
    {"id": 13, "question": "The banks should be nationalized", "effects": {"right": -1}},
    {"id": 14, "question": "The government should provide free healthcare for all citizens", "effects": {"right": -1}},
    {"id": 15, "question": "Many of the so-called conspiracy theories are just facts the mainstream media don't want us to know", "effects": {"auth": 1}},
    {"id": 16, "question": "The government is carrying out medical experiments on the public without their consent or knowledge", "effects": {"auth": 1}},
    {"id": 17, "question": "NATO should be abolished", "effects": {"auth": 1}},
    {"id": 18, "question": "The CIA should be abolished", "effects": {"auth": 1}},
    {"id": 19, "question": "If voting could change anything, they'd make it illegal", "effects": {"auth": 1}},
    {"id": 20, "question": "I believe my current government doesn't represent the will of the people and see it as fundamentally illegitimate", "effects": {"auth": 1}},
    {"id": 21, "question": "In the event of war I wouldn't be willing to fight for my government as it currently exists", "effects": {"auth": 1}},
    {"id": 22, "question": "Election fraud in my country is widespread and it's very likely some elections were stolen", "effects": {"auth": 1}},
    {"id": 23, "question": "The government should work with private companies to stop the spread of misinformation and conspiracy theories on social media", "effects": {"auth": -1}},
    {"id": 24, "question": "Populism and extremism on both sides of the political spectrum is a threat to our democracy and should be combated", "effects": {"auth": -1}},
    {"id": 25, "question": "Medical misinformation regarding COVID-19 or vaccination conspiracy theories are a threat to public health and should be censored", "effects": {"auth": -1}},
    {"id": 26, "question": "Israel is the only democracy in the Middle East and deserves our support", "effects": {"auth": -1}},
    {"id": 27, "question": "We should support Ukraine against Russian aggression", "effects": {"auth": -1}},
    {"id": 28, "question": "Economic sanctions against authoritarian rogue states such as Iran, Cuba, North Korea and/or Russia are a good idea", "effects": {"auth": -1}},
    {"id": 29, "question": "Civilians should not be allowed to own military grade weapons", "effects": {"auth": -1}},
    {"id": 30, "question": "Abortion should be legal in all cases", "effects": {"prog": 1}},
    {"id": 31, "question": "Euthanasia and doctor-assisted suicide should be legal", "effects": {"prog": 1}},
    {"id": 32, "question": "Victimless crimes should not be punished", "effects": {"prog": 1}},
    {"id": 33, "question": "Marijuana should be legalized or decriminalized", "effects": {"prog": 1}},
    {"id": 34, "question": "I consider myself a citizen of the world", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is an oppressive social construct that should be radically redefined and/or abolished", "effects": {"prog": 1}},
    {"id": 36, "question": "Multiculturalism is good for our society", "effects": {"prog": 1}},
    {"id": 37, "question": "Criminal justice should focus more on rehabilitation than punishment", "effects": {"prog": 1}},
    {"id": 38, "question": "These days, openness about sex has gone too far", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children", "effects": {"prog": -1}},
    {"id": 40, "question": "Women should dress modestly", "effects": {"prog": -1}},
    {"id": 41, "question": "The death penalty should exist for certain crimes", "effects": {"prog": -1}},
    {"id": 42, "question": "Pornography and prostitution are harmful and should be banned", "effects": {"prog": -1}},
    {"id": 43, "question": "Everyone needs a father figure in their life", "effects": {"prog": -1}},
    {"id": 44, "question": "I'd rather watch a military parade than a pride parade", "effects": {"prog": -1}},
    {"id": 45, "question": "Men are becoming too feminine and weak. They should be encouraged to rediscover their masculinity", "effects": {"prog": -1}}
];
